function [z, k] = maxPoolingLayer(a, mapSize, scale)
    z = arrayfun(@(i) ...
            arrayfun(@(j) ...
                maxPooling(a(scale * (i - 1) + 1:scale * i, scale * (j - 1) + 1:scale * j, :)), ...
                1:mapSize(2), 'UniformOutput', false), ...
            1:mapSize(1), 'UniformOutput', false);
    z = cell2mat(cellfun(@(maxArray) transpose3d(cell2mat(maxArray)), z, 'UniformOutput', false));
    z = transpose3d(z);
    k = expand(z, [scale, scale, 1]) == a;
end